name: future_goodies
author: Wilker Lúcio <wilkerlucio@gmail.com>
version: 0.2.0
homepage: https://github.com/wilkerlucio/future_goodies
description: Future helper libraries for async management.
dev_dependencies:
  barrier: any
